apiVersion: v1
kind: Secret

metadata:
  name: spring-secret
  namespace: default

# Opaque is the default generic type for arbitrary key-value secrets.
type: Opaque

# Values MUST be base64-encoded.
# echo -n 'app'         | base64  →  YXBw
# echo -n 'supersecret' | base64  →  c3VwZXJzZWNyZXQ=
data:
  DB_USERNAME: YXBw
  DB_PASSWORD: c3VwZXJzZWNyZXQ=
